[package]
name = "midi_fader"
version = "0.1.0"
authors = ["Kevin Cuzner <kevin@kevincuzner.com>"]

[dependencies]
clap = "2.32.0"
error-chain = "0.12.0"

[target.'cfg(target_os="linux")'.dependencies]
udev = "0.2.0"

