[package]
name = "midi_fader"
version = "0.1.0"
authors = ["Kevin Cuzner <kevin@kevincuzner.com>"]

[dependencies]
clap = "2.32.0"
error-chain = "0.12.0"
tokio = "0.1.11"
mio = "0.6.16"
libc = "0.2"
futures = "0.1.24"

[target.'cfg(target_os="linux")'.dependencies]
udev = "0.2.0"

